apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_USER: Y2FuZGlkYXRl #candidate
  MYSQL_PASSWORD: dGVzdDEyMw== #password
